### ISSUE TITLE
Plan on releasing code

### ISSUE THREAD

**Issue by wjc2830** [naver-ai/rewas#1]
Hi, there. Appreciate for great work contribution. I am wondering what' s your plan to release the code.

**Comment by lee-jiyoung** [comment]
@wjc2830 Thank you for your interest in our work! The code is under internal review so it will be released soon within the next week.

**Comment by wjc2830** [comment]
Cool, thanks for your prompt reply. Looking forward to the code.

**Comment by slliugit** [comment]
Looking forward to the code！

**Comment by slliugit** [comment]
Hello, I am wondering what' s your plan to release the code.

**Comment by lee-jiyoung** [comment]
@wjc2830 @slliugit Thank you for waiting! Now we release the code :)

**Comment by slliugit** [comment]
> @wjc2830 @slliugit Thank you for waiting! Now we release the code :)

Wow！Thank you!

**Comment by slliugit** [comment]
> @wjc2830 @slliugit Thank you for waiting! Now we release the code :)

Wow! Thank you so much for your reply! However, it seems that only the test part of the released code, is it possible to provide training scripts?

**Comment by lee-jiyoung** [comment]
@slliugit
Sorry, there are no plans to release the training code at this time. 
If you need to train, you can easily learn ReWaS by modifying the following codes a little bit.

https://github.com/haoheliu/AudioLDM-training-finetuning/blob/main/audioldm_train/train/latent_diffusion.py
https://github.com/lllyasviel/ControlNet/blob/main/tutorial_train.py

If you have any questions about training, please let me know.

**Comment by slliugit** [comment]
> @slliugit Sorry, there are no plans to release the training code at this time.抱歉，目前没有发布训练代码的计划。 If you need to train, you can easily learn ReWaS by modifying the following codes a little bit.如果需要培训，可以通过稍微修改以下代码来轻松学习 ReWaS。
> 
> https://github.com/haoheliu/AudioLDM-training-finetuning/blob/main/audioldm_train/train/latent_diffusion.py https://github.com/lllyasviel/ControlNet/blob/main/tutorial_train.py
> 
> If you have any questions about training, please let me know.如果您对培训有任何疑问，请告诉我。

Ok! Thank you so much!
