### ISSUE TITLE
Where the 24-01-04T16-39-21.pt mentioned in ckpt?

### ISSUE THREAD

**Issue by slliugit** [naver-ai/rewas#2]
Hi, I have download the checkpoints as the two links, but didn't find the 24-01-04T16-39-21.pt.

**Comment by slliugit** [comment]
The checkpoints in the second link [AudioLDM-training] only contain the 
![微信图片_20241022095653](https://github.com/user-attachments/assets/9ddf758b-d23d-4df5-8083-85b9b36f3ee2)

**Comment by lee-jiyoung** [comment]
We update the download link (https://github.com/v-iashin/Synchformer?tab=readme-ov-file#audio-visual-synchronization-models).
